baseURL = "https://concurrence.io"
languageCode = "en-us"
title = "Concurrence"
theme = "hugo-theme-learn"
[params]
  subtitle = "Decentralized Oracle Platform"
  author = "Austin Thomas Griffith M.S. E.E."
  themeVariant = "blue"
  disableSearch = true
