baseURL = "https://pyth.io"
languageCode = "en-us"
title = "Pyth.io"
theme = "hugo-theme-learn"
[params]
  subtitle = "Decentralized Blockchain Oracle"
  author = "Austin Thomas Griffith M.S. E.E."
  themeVariant = "blue"
  disableSearch = true
